//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

pub use super::article::Entity as Article;
pub use super::folder::Entity as Folder;
pub use super::language::Entity as Language;
pub use super::person::Entity as Person;
