export enum ViewKey {
    HOME = "HOME",
    SETTINGS = "SETTINGS",
    ARTICLE_EDITOR = "ARTICLE_EDITOR",
    DICTIONARY_EDITOR = "DICTIONARY_EDITOR",
}

export enum ModalKey {
    PROJECT_CREATOR = "PROJECT_CREATOR",
    ARTICLE_CREATOR = "ARTICLE_CREATOR",
}

export enum ContextMenuKey {
    NAV_BAR_FOLDER_NODE = "NAV_BAR_FOLDER_NODE",
    NAV_BAR_ARTICLE_NODE = "NAV_BAR_ARTICLE_NODE",
}
